# Generated by Django 6.0.2 on 2026-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_deal_dealitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("template", models.CharField(max_length=100)),
            ],
        ),
    ]
