# Generated by Django 6.0.2 on 2026-02-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="channel",
            field=models.CharField(
                choices=[
                    ("world", "Мировой"),
                    ("location", "Локация"),
                    ("trade", "Торговый"),
                    ("group", "Группа"),
                    ("clan", "Клан"),
                    ("alliance", "Альянс"),
                ],
                default="world",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clan",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="led_clans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
