# Generated by Django 6.0.2 on 2026-02-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_chatmessage_channel_alter_clan_leader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="channel",
            field=models.CharField(
                choices=[
                    ("world", "Мировой"),
                    ("location", "Локация"),
                    ("trade", "Торговый"),
                    ("group", "Группа"),
                    ("clan", "Клан"),
                    ("alliance", "Альянс"),
                    ("private", "Личный"),
                    ("system", "Системный"),
                ],
                default="world",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
