# Generated by Django 6.0.2 on 2026-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_equipped", models.BooleanField(default=False)),
                ("slot", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Оружие"),
                            ("armor", "Броня"),
                            ("helmet", "Шлем"),
                            ("gloves", "Перчатки"),
                            ("boots", "Сапоги"),
                            ("shield", "Щит"),
                            ("ring", "Кольцо"),
                            ("amulet", "Амулет"),
                            ("potion", "Зелье"),
                        ],
                        max_length=20,
                    ),
                ),
                ("req_level", models.IntegerField(default=1)),
                ("req_strength", models.IntegerField(default=0)),
                ("req_agility", models.IntegerField(default=0)),
                ("req_intuition", models.IntegerField(default=0)),
                ("bonus_strength", models.IntegerField(default=0)),
                ("bonus_agility", models.IntegerField(default=0)),
                ("bonus_intuition", models.IntegerField(default=0)),
                ("bonus_endurance", models.IntegerField(default=0)),
                ("bonus_armor", models.IntegerField(default=0)),
                ("bonus_min_dmg", models.IntegerField(default=0)),
                ("bonus_max_dmg", models.IntegerField(default=0)),
                ("price_gold", models.IntegerField(default=0)),
                ("price_silver", models.IntegerField(default=0)),
            ],
        ),
    ]
