# Generated by Django 6.0.2 on 2026-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommissionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_silver", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_equipped", models.BooleanField(default=False)),
                ("slot", models.CharField(blank=True, max_length=50, null=True)),
                ("durability_current", models.IntegerField(default=0)),
                ("durability_max", models.IntegerField(default=100)),
                ("enhancement_level", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Оружие"),
                            ("armor", "Броня"),
                            ("helmet", "Шлем"),
                            ("gloves", "Перчатки"),
                            ("boots", "Сапоги"),
                            ("shield", "Щит"),
                            ("ring", "Кольцо"),
                            ("amulet", "Амулет"),
                            ("belt", "Пояс"),
                            ("bracers", "Наручи"),
                            ("cloak", "Плащ"),
                            ("potion", "Зелье"),
                            ("scroll", "Свиток"),
                            ("quest", "Квестовый предмет"),
                            ("gift", "Подарок"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("equipment", "Экипировка"),
                            ("elixirs", "Эликсиры"),
                            ("scrolls", "Свитки"),
                            ("quest", "Квестовые предметы"),
                            ("gifts", "Подарки"),
                        ],
                        default="equipment",
                        max_length=20,
                    ),
                ),
                ("req_level", models.IntegerField(default=1)),
                ("req_strength", models.IntegerField(default=0)),
                ("req_agility", models.IntegerField(default=0)),
                ("req_intuition", models.IntegerField(default=0)),
                ("bonus_strength", models.IntegerField(default=0)),
                ("bonus_agility", models.IntegerField(default=0)),
                ("bonus_intuition", models.IntegerField(default=0)),
                ("bonus_endurance", models.IntegerField(default=0)),
                ("bonus_armor", models.IntegerField(default=0)),
                ("bonus_min_dmg", models.IntegerField(default=0)),
                ("bonus_max_dmg", models.IntegerField(default=0)),
                ("restore_hp", models.IntegerField(default=0)),
                ("restore_mp", models.IntegerField(default=0)),
                ("price_gold", models.IntegerField(default=0)),
                ("price_silver", models.IntegerField(default=0)),
            ],
        ),
    ]
