# Generated by Django 6.0.2 on 2026-02-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("helmet", "Helmet"),
                            ("gloves", "Gloves"),
                            ("boots", "Boots"),
                            ("shield", "Shield"),
                            ("ring", "Ring"),
                            ("amulet", "Amulet"),
                            ("potion", "Potion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("req_level", models.IntegerField(default=1)),
                ("req_strength", models.IntegerField(default=0)),
                ("req_agility", models.IntegerField(default=0)),
                ("req_intuition", models.IntegerField(default=0)),
                ("bonus_strength", models.IntegerField(default=0)),
                ("bonus_agility", models.IntegerField(default=0)),
                ("bonus_intuition", models.IntegerField(default=0)),
                ("bonus_endurance", models.IntegerField(default=0)),
                ("bonus_armor", models.IntegerField(default=0)),
                ("bonus_min_dmg", models.IntegerField(default=0)),
                ("bonus_max_dmg", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_equipped", models.BooleanField(default=False)),
                ("slot", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="characters.character",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
            ],
        ),
    ]
