# Generated by Django 6.0.2 on 2026-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="durability_current",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="durability_max",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="enhancement_level",
            field=models.IntegerField(default=0),
        ),
    ]
