# Generated by Django 6.0.2 on 2026-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="durability_max",
            field=models.IntegerField(default=100),
        ),
    ]
