# Generated by Django 6.0.2 on 2026-02-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_inventoryitem_durability_current_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("equipment", "Экипировка"),
                    ("elixirs", "Эликсиры"),
                    ("scrolls", "Свитки"),
                    ("quest", "Квестовые предметы"),
                    ("gifts", "Подарки"),
                ],
                default="equipment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("weapon", "Оружие"),
                    ("armor", "Броня"),
                    ("helmet", "Шлем"),
                    ("gloves", "Перчатки"),
                    ("boots", "Сапоги"),
                    ("shield", "Щит"),
                    ("ring", "Кольцо"),
                    ("amulet", "Амулет"),
                    ("belt", "Пояс"),
                    ("bracers", "Наручи"),
                    ("cloak", "Плащ"),
                    ("potion", "Зелье"),
                    ("scroll", "Свиток"),
                    ("quest", "Квестовый предмет"),
                    ("gift", "Подарок"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CommissionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_silver", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.inventoryitem",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
