# Generated by Django 6.0.2 on 2026-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_durability_max"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("weapon", "Оружие"),
                    ("armor", "Броня"),
                    ("helmet", "Шлем"),
                    ("gloves", "Перчатки"),
                    ("boots", "Сапоги"),
                    ("shield", "Щит"),
                    ("ring", "Кольцо"),
                    ("amulet", "Амулет"),
                    ("belt", "Пояс"),
                    ("bracers", "Наручи"),
                    ("cloak", "Плащ"),
                    ("potion", "Зелье"),
                    ("scroll", "Свиток"),
                    ("quest", "Квестовый предмет"),
                    ("gift", "Подарок"),
                    ("misc", "Разное"),
                ],
                max_length=20,
            ),
        ),
    ]
