# Generated by Django 6.0.2 on 2026-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_item_category_alter_item_item_type_commissionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="durability_current",
            field=models.IntegerField(default=0),
        ),
    ]
