# Generated by Django 6.0.2 on 2026-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_inventoryitem_durability_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="restore_hp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="restore_mp",
            field=models.IntegerField(default=0),
        ),
    ]
