# Generated by Django 6.0.2 on 2026-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="diamonds",
            field=models.IntegerField(default=0, verbose_name="Алмазы"),
        ),
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Уровень"),
        ),
    ]
