# Generated by Django 6.0.2 on 2026-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_diamonds_alter_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alliance",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Альянс"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="clan",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Клан"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="monster_draws",
            field=models.IntegerField(default=0, verbose_name="Ничьих (мобы)"),
        ),
        migrations.AddField(
            model_name="user",
            name="monster_losses",
            field=models.IntegerField(default=0, verbose_name="Поражений (мобы)"),
        ),
        migrations.AddField(
            model_name="user",
            name="monster_wins",
            field=models.IntegerField(default=0, verbose_name="Побед (мобы)"),
        ),
        migrations.AddField(
            model_name="user",
            name="player_draws",
            field=models.IntegerField(default=0, verbose_name="Ничьих (игроки)"),
        ),
        migrations.AddField(
            model_name="user",
            name="player_losses",
            field=models.IntegerField(default=0, verbose_name="Поражений (игроки)"),
        ),
        migrations.AddField(
            model_name="user",
            name="player_wins",
            field=models.IntegerField(default=0, verbose_name="Побед (игроки)"),
        ),
        migrations.AddField(
            model_name="user",
            name="sub_levels_completed",
            field=models.IntegerField(default=0, verbose_name="Завершено подуровней"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_xp",
            field=models.IntegerField(default=0, verbose_name="Всего опыта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="current_mp",
            field=models.FloatField(default=0, verbose_name="Текущее MP"),
        ),
        migrations.AlterField(
            model_name="user",
            name="intelligence",
            field=models.IntegerField(default=0, verbose_name="Интеллект"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_location",
            field=models.CharField(
                default="novice_hall", max_length=100, verbose_name="Локация"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="spirit",
            field=models.IntegerField(default=0, verbose_name="Дух"),
        ),
        migrations.AlterField(
            model_name="user",
            name="stat_points",
            field=models.IntegerField(default=5, verbose_name="Свободные очки"),
        ),
        migrations.AlterField(
            model_name="user",
            name="wisdom",
            field=models.IntegerField(default=0, verbose_name="Мудрость"),
        ),
    ]
