# Generated by Django 6.0.2 on 2026-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("level", models.IntegerField(default=1)),
                ("exp", models.IntegerField(default=0)),
                ("strength", models.IntegerField(default=3)),
                ("agility", models.IntegerField(default=3)),
                ("intuition", models.IntegerField(default=3)),
                ("endurance", models.IntegerField(default=3)),
                ("intelligence", models.IntegerField(default=3)),
                ("wisdom", models.IntegerField(default=3)),
                ("spirit", models.IntegerField(default=3)),
                ("stat_points", models.IntegerField(default=0)),
                ("current_hp", models.FloatField(default=60)),
                ("current_mp", models.FloatField(default=50)),
                (
                    "location_id",
                    models.CharField(default="central_square", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
