# Generated by Django 6.0.2 on 2026-02-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("in_progress", "В процессе"),
                            ("finished", "Завершен"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "battle_type",
                    models.CharField(
                        choices=[("pvp", "PvP"), ("pve", "PvE")], max_length=20
                    ),
                ),
                ("current_turn", models.IntegerField(default=1)),
                ("log", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BattleParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("npc_id", models.CharField(blank=True, max_length=100, null=True)),
                ("team", models.IntegerField()),
                ("hp_snapshot", models.IntegerField()),
                ("stats_snapshot", models.JSONField()),
                ("is_winner", models.BooleanField(default=False)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="battles.battle",
                    ),
                ),
            ],
        ),
    ]
