# Generated by Django 6.0.2 on 2026-02-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("battles", "0001_initial"),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.character",
            ),
        ),
    ]
