# Generated by Django 6.0.2 on 2026-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=0)),
                ("hp", models.IntegerField(default=50)),
                ("strength", models.IntegerField(default=3)),
                ("agility", models.IntegerField(default=3)),
                ("intuition", models.IntegerField(default=3)),
                ("silver_min", models.IntegerField(default=5)),
                ("silver_max", models.IntegerField(default=10)),
                ("exp_min", models.IntegerField(default=10)),
                ("exp_max", models.IntegerField(default=20)),
            ],
        ),
    ]
